services:
  # ui:
  #     container_name: ui
  #     build:
  #         context: ./ui
  #         dockerfile: Dockerfile
  #     depends_on:
  #         - redis
  #         - api
  #     ports:
  #         - "3000:3000"
  #     volumes:
  #         - ./client:/usr/src/app/ui
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=5000
    links:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app/api
  redis:
    container_name: cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./server:/usr/src/app/cache
